# Generated by Django 4.0.5 on 2022-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_alter_ad_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
